# -*- coding: utf-8 -*-
"""Minima_Accion.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10fcNe8kFO0fqJwCFFZALFcynjuR79Xzj
"""

!pip install astropy

!pip install matplotlib

!pip install numpy

!pip install corner

!pip install scipy

# =============================================================================
# LABORATORIO UAT/UPC: SIMULACIÓN DE TIEMPO DE TÚNEL NEGATIVO (CORREGIDO)
# Correcciones:
# 1. Dominio espacial ampliado (L=400) para evitar envolventes periódicas.
# 2. Tiempo de simulación reducido (2000 pasos) para detener antes de que
#    el paquete reflejado dé la vuelta.
# 3. Medición correcta sobre la onda transmitida genuina.
# =============================================================================

!pip install -q numpy scipy matplotlib

import numpy as np
import matplotlib.pyplot as plt
from scipy.constants import hbar, pi
from scipy.fft import fft, ifft, fftfreq
from scipy.integrate import simpson

print("🚀 Laboratorio UAT/UPC: Simulación de Túnel Cuántico (Corregido)\n")

# =============================================================================
# 1. PARÁMETROS CORREGIDOS
# =============================================================================
N = 4096           # Más puntos para mantener resolución en dominio mayor
L = 400.0          # Dominio ampliado para evitar efecto espejo
dx = L / N
dt = 0.005
x = np.linspace(-L/2, L/2, N)

# Paquete de ondas inicial
x0 = -50.0
k0 = 10.0
sigma = 3.0

# Barrera de potencial (V0 > E para túnel)
V0 = 80.0
a = 1.0
x_barrera = 0.0

E_kin = k0**2 / 2

# Inicialización del paquete
def inicializar_paquete(x, x0, k0, sigma):
    return np.exp(-(x - x0)**2 / (2 * sigma**2)) * np.exp(1j * k0 * x)

psi = inicializar_paquete(x, x0, k0, sigma)

# Potencial de barrera
def potencial(x, V0, a, x_barrera):
    return V0 * (np.abs(x - x_barrera) < a/2)

V = potencial(x, V0, a, x_barrera)

# =============================================================================
# 2. EVOLUCIÓN SPLIT‑STEP
# =============================================================================
def split_step(psi, V, dt, dx, k):
    psi_k = fft(psi)
    psi_k *= np.exp(-1j * k**2 * dt / 4)
    psi = ifft(psi_k)
    psi *= np.exp(-1j * V * dt)
    psi_k = fft(psi)
    psi_k *= np.exp(-1j * k**2 * dt / 4)
    psi = ifft(psi_k)
    return psi

k = 2 * pi * fftfreq(N, dx)

# Tiempo de simulación reducido para aislar la transmisión
num_pasos = 2000
guardar_cada = 50
densidades = []
tiempos_guardados = []

for paso in range(num_pasos):
    if paso % guardar_cada == 0:
        densidades.append(np.abs(psi)**2)
        tiempos_guardados.append(paso * dt)
    psi = split_step(psi, V, dt, dx, k)

densidades = np.array(densidades)

# =============================================================================
# 3. CÁLCULO DEL TIEMPO DE TRÁNSITO SOBRE LA ONDA TRANSMITIDA REAL
# =============================================================================
psi_final = psi

# Solo consideramos la región a la derecha de la barrera
indices_derecha = x > (x_barrera + a/2)
x_trans = x[indices_derecha]
psi_trans = psi_final[indices_derecha]

# Pico de la onda transmitida (ignorando posibles residuos de la reflejada)
idx_pico_trans = np.argmax(np.abs(psi_trans)**2)
x_pico_trans = x_trans[idx_pico_trans]
t_total_sim = num_pasos * dt

# Velocidad media del pico transmitido
v_media = (x_pico_trans - x0) / t_total_sim

# Punto de observación
x_obs = 30.0
t_vuelo_libre = (x_obs - x0) / k0
t_real = (x_obs - x0) / v_media
t_retardo = t_real - t_vuelo_libre

print(f"Posición del pico transmitido: {x_pico_trans:.2f}")
print(f"Velocidad media del pico: {v_media:.3f}")
print(f"Velocidad de grupo libre: {k0:.3f}")
print(f"Tiempo de retardo adimensional: {t_retardo:.6f}")

# =============================================================================
# 4. CONEXIÓN CON UAT/UPC
# =============================================================================
t0_fisico = 1e-15  # 1 femtosegundo por unidad adimensional
t_retardo_fisico = t_retardo * t0_fisico

l_planck = 1.616e-35
t_planck = 5.391e-44

print(f"\n=== RESULTADOS DEL ANÁLISIS ===")
print(f"Energía cinética del paquete (E): {E_kin:.3f}")
print(f"Altura de la barrera (V0): {V0}")
print(f"Ancho de la barrera (a): {a}")
print(f"Relación E/V0: {E_kin/V0:.3f} (E < V0 -> Régimen de túnel)")
print(f"Tiempo de retardo adimensional: {t_retardo:.6f}")
print(f"Tiempo de retardo físico estimado: {t_retardo_fisico:.3e} s")
print(f"Tiempo de Planck: {t_planck:.3e} s")
print(f"Relación retardo / t_Planck: {t_retardo_fisico / t_planck:.3e}")

if t_retardo < 0:
    print("\n🔬 Se ha observado un TIEMPO DE TRÁNSITO NEGATIVO.")
    print("   El pico de la onda transmitida emerge antes de lo esperado por vuelo libre.")
    print("\n🌌 Interpretación UAT/UPC:")
    print(f"   La magnitud del tiempo negativo ({abs(t_retardo_fisico):.3e} s) es")
    print(f"   {abs(t_retardo_fisico)/t_planck:.1e} veces el tiempo de Planck.")
    print("   Esta fluctuación es minúscula comparada con la escala de Planck,")
    print("   pero está dentro del margen permitido por el límite de coherencia")
    print(f"   causal (κ_crit ≈ 10⁻⁷⁸). El principio de mínima acción selecciona una")
    print("   historia cuántica con tiempo aplicable localmente negativo,")
    print("   sin violar la causalidad global.")
else:
    print("\n🔬 El tiempo de tránsito fue positivo en esta configuración.")
    print("   (Si aún es positivo, probar con una barrera más ancha (a=2) o menor energía (k0=8)).")

# =============================================================================
# 5. GRÁFICOS
# =============================================================================
plt.figure(figsize=(14, 10))

# Evolución de la densidad
plt.subplot(2, 2, 1)
plt.imshow(densidades, aspect='auto', extent=[x[0], x[-1], tiempos_guardados[-1], tiempos_guardados[0]],
           cmap='hot')
plt.colorbar(label='|ψ|²')
plt.xlabel('Posición x')
plt.ylabel('Tiempo')
plt.title('Evolución del paquete de ondas (dominio ampliado)')
plt.fill_between([x_barrera - a/2, x_barrera + a/2], 0, tiempos_guardados[-1], alpha=0.3, color='blue')

# Perfil inicial y final
plt.subplot(2, 2, 2)
plt.plot(x, np.abs(psi)**2, label='|ψ|² en t final')
plt.plot(x, np.abs(inicializar_paquete(x, x0, k0, sigma))**2, '--', label='|ψ|² en t=0')
plt.fill_between([x_barrera - a/2, x_barrera + a/2], 0, np.max(np.abs(psi)**2)*1.1, alpha=0.3, color='blue', label='Barrera')
plt.xlabel('Posición x')
plt.ylabel('Densidad de probabilidad')
plt.title('Comparación de paquetes de onda')
plt.xlim([-100, 200])  # Zoom a la región de interés
plt.legend()
plt.grid(alpha=0.3)

# Fase de la onda transmitida
plt.subplot(2, 2, 3)
plt.plot(x_trans, np.unwrap(np.angle(psi_trans)), 'g-')
plt.xlabel('Posición x (transmitida)')
plt.ylabel('Fase (rad)')
plt.title('Fase de la función de onda transmitida')
plt.grid(alpha=0.3)

# Resumen UAT/UPC
plt.subplot(2, 2, 4)
plt.text(0.1, 0.9, f"Tiempo de retardo: {t_retardo:.4f} (adim.)", transform=plt.gca().transAxes, fontsize=12)
plt.text(0.1, 0.7, f"Equivalente a: {t_retardo_fisico:.3e} s", transform=plt.gca().transAxes, fontsize=12)
plt.text(0.1, 0.5, f"Tiempo de Planck: {t_planck:.3e} s", transform=plt.gca().transAxes, fontsize=12)
if t_retardo < 0:
    plt.text(0.1, 0.3, "UAT/UPC: Fluctuación negativa permitida", transform=plt.gca().transAxes, fontsize=12)
else:
    plt.text(0.1, 0.3, "Aún positivo; ajuste parámetros", transform=plt.gca().transAxes, fontsize=12)
plt.axis('off')
plt.title('Resumen UAT/UPC')

plt.tight_layout()
plt.savefig('tunel_cuantico_uat_upc.png', dpi=150)
plt.show()

print("\n🎲 Laboratorio completado. El dominio ampliado evita el efecto espejo y captura la transmisión real.")